### ISSUE TITLE
List Bank statements with correct labeling

### ISSUE THREAD

**Issue by Alejo-digilytics** [Alejo-digilytics/NER#1]
Make a list with all the banks and format types for bank statements that we can extract the entities with very high accuracy. If there are problems do write them in the list. They will be added as another issue. This is for NLP data (text data)
Just verify that the entities are right

**Comment by Shakya-py** [comment]
Bank        format_type     accuracy      status
Natwest    pdf                   99+            done
RBS           pdf                   99+            done
RBS           txn                    --               working
Natwest    txn                    --                --
HSBC         pdf                   --               --
HSBC         txn                   --               --
Santander pdf                   --               --
Santander txn                   --               --
Barclays    pdf                   --               --
Barclays    txn                   --                --
lloyds       pdf                   --                --
lloyds       txn                   --                --
Note: no issue has been found yet for scripts that had completed.

**Comment by Alejo-digilytics** [comment]
please let me know if there is some update, if you checked some other bank statements today or tomorrow

**Comment by Shakya-py** [comment]
Bank format_type accuracy status
Natwest pdf 99+ done
RBS pdf 99+ done
RBS txn 99+ done
Natwest txn -- --
HSBC pdf 99+ done
HSBC txn -- working
Santander pdf -- --
Santander txn -- --
Barclays pdf -- --
Barclays txn -- --
lloyds pdf -- --
lloyds txn -- --
Note: no issue has been found yet for scripts that had completed.

**Comment by Alejo-digilytics** [comment]
Please update the list again tomorrow 05/02/2021 considering that it is the NLP case. I am going to add an issue for the addresses

**Comment by Shakya-py** [comment]
Bank format_type accuracy status
Natwest pdf 99+ done
RBS pdf 99+ done
RBS txn -- working
Natwest txn -- --
HSBC pdf 99+ done
HSBC txn 99+ done
Santander pdf -- working
Santander txn -- --
Barclays pdf -- --
Barclays txn -- --
lloyds pdf -- --
lloyds txn -- --

**Comment by Shakya-py** [comment]
Bank format_type accuracy status
Natwest pdf 99+ done
RBS pdf 99+ done
RBS txn -- done
HSBC pdf 99+ done
Santander pdf 99+ done
Barclays pdf -- --
Lloyds pdf -- working

**Comment by Shakya-py** [comment]
Bank format_type accuracy status
Natwest pdf 99+ done
RBS pdf 99+ done
RBS txn -- done
HSBC pdf 99+ done
Santander pdf 99+ done
Barclays pdf -- --
Lloyds pdf -- working(Issue: lloyds pdfs returning anonymous text which is not human interpretable) @Alejo-digilytics @neerajvashistha

**Comment by Alejo-digilytics** [comment]
We will check it the three along the day

**Comment by Shakya-py** [comment]
Bank format_type accuracy status
Natwest pdf 99+ done
RBS pdf 99+ done
RBS txn -- done
HSBC pdf 99+ done
Santander pdf 99+ done
Barclays pdf 99+ done
Lloyds pdf -- working(due to the previous issue moving to Microsoft cognitive services for lloyds)

**Comment by Shakya-py** [comment]
Bank format_type accuracy status
Natwest pdf 99+ done
RBS pdf 99+ done
RBS txn -- done
HSBC pdf 99+ done
Santander pdf 99+ done
Barclays pdf 99+ done
Lloyds pdf 99+ done

**Comment by Alejo-digilytics** [comment]
> 
> 
> Bank format_type accuracy status
> Natwest pdf 99+ done
> RBS pdf 99+ done
> RBS txn -- done
> HSBC pdf 99+ done
> Santander pdf 99+ done
> Barclays pdf 99+ done
> Lloyds pdf 99+ done

Gret that you got also Lloyds with cognitive.
Didi you manage what Neeraj said about running the scripts automaticly?

**Comment by Shakya-py** [comment]
not yet right now i'm moving scripts from root to bankstatement_all folder to run scripts there...

**Comment by Shakya-py** [comment]
| Bank name           | Status  |    Remarks   | No. of Pdfs |
|-------------------- | --------| ------------- | ------------|

**Comment by Alejo-digilytics** [comment]
Thank you Ramakant, now it is much more clear. Let me know whenever you are done with Yorkshire bank

**Comment by Alejo-digilytics** [comment]
Please update the final list with all the bank statements that we have. To show it for reports.

**Comment by Shakya-py** [comment]
| Bank name           | Status  |    Remarks   |
|-------------------- | --------| ------------- |
| Barclays_pdf         | Done   |  --                |
| Barclays_trx          | Done   | -- |
| Co-operative Bank|  --       | NE |
| Coutts |  --       | NE |
| Danske Bank |  --       | NE |
| First Trust Bank  |  --       | NE |
| Habib Bank |  --       | NE  |
| HSBC_trx |  --       | NE  |
| HSBC_pdf |  Done       | -- |
| Liberis Bank |  --       | NE |
| Lloyds_pdf |  --       | NE  |
| Lloys_trx |  Done       | --  |
| Metro Bank |  --       | NE  |
| Natwest_pdf |  Done       | --  |
| Natwest_trx |  Done       |  --  |
| RBS_trx |  --       | NE  |
| RBS_pdf |  Done       | --  |
| Santander_trx |  --       | NE |
| Santander_pdf |  Done       | -- |
| TSB |  --       | NE |
| Yorkshire bank | Done      | -- |

NE : Not enough pdfs (Minimum 30 required)
Total of 532 NLP labelled text generated

**Comment by Shakya-py** [comment]
| Bank name           | No of files  |    Remarks   |
|-------------------- | --------| ------------- |
| Barclays_pdf         | 224   |  --                |
| Barclays_trx          | 56   | -- |
| HSBC_pdf |  84      | -- |
| Lloys_trx |  58       | --  |
| Natwest_pdf |  58       | --  |
| Natwest_trx |  16       |  --  |
| RBS_pdf |  23      | --  |
| Santander_pdf |  35      | -- |
| Yorkshire bank | 17     | -- |
