### ISSUE TITLE
Create a set of examples for preprocessing

### ISSUE THREAD

**Issue by Alejo-digilytics** [Alejo-digilytics/NER#2]
Create a few examples for LLM with Natwest following the schema designed by Neeraj.
Clarification: It means an input example for LLM, just the JSON file. Since it is already processed it is no longer confidential data and we can share it by email. It is like one of those JSON files shared by Ramakant but being completely sure that is right.

**Comment by neerajvashistha** [comment]
Please provide the server details and path.

**Comment by neerajvashistha** [comment]
Completed!
