### ISSUE TITLE
Labelling the NLP/text data for all our data

### ISSUE THREAD

**Issue by Alejo-digilytics** [Alejo-digilytics/NER#3]
Run the scripts for all our bank statements in our data set.
create the NLP data set for fune tuning

**Comment by Shakya-py** [comment]
Natwest and RBS  NLP dataset created

**Comment by Shakya-py** [comment]
Natwest, RBS, HSBC has done, Santander Started....

**Comment by Shakya-py** [comment]
Natwest, RBS, HSBC, Santander, Barclays has done, Lloyds started

**Comment by Shakya-py** [comment]
all 7 banks done
