### ISSUE TITLE
Wrong labels in the NLP NER bank statements dataset

### ISSUE THREAD

**Issue by Alejo-digilytics** [Alejo-digilytics/NER#5]
Correct the missing labels for addresses coming from the NLP scripts

**Comment by Shakya-py** [comment]
I did not find any incorrect labels for the address could you navigate me to the error?

**Comment by Alejo-digilytics** [comment]
Just to clarify. You were already doing this task. They are the AA and AN that you are correcting since yesterday.
I will take a look to Natwest and RBS cases along the morning

**Comment by neerajvashistha** [comment]
As discussed today on the call, possible solutions are
1. add all the lines to stack, pop elements if not a digit, have keywords like LTD, LIMITED, PLC, LLC -> create a list of such keywords.
2. use open-source libraries like https://github.com/vladimarius/pyap and there are some other too
3. or build a NN like for example https://github.com/jasonrig/address-net, this in particular is for Australia, this would be for worst case scenario.

**Comment by Shakya-py** [comment]
able to extract AA and AN tag correctly for 
1.Natwest
2.RBS
3.HSBC
4.Santander
5.Barclays

**Comment by Shakya-py** [comment]
all detected correctly
