### ISSUE TITLE
List bank statements adapted to computer vision

### ISSUE THREAD

**Issue by Alejo-digilytics** [Alejo-digilytics/NER#9]
Create a list it was done for NLP data where they are registered all the banks and their types and for which of them do we have a script to extract the entities

**Comment by Shakya-py** [comment]
completed

**Comment by Shakya-py** [comment]
| Bank name           | Status  |    Remarks   |
|-------------------- | --------| ------------- |
| Barclays_pdf         | Done   |  --                |
| Barclays_trx          | Done   | -- |
| Co-operative Bank|  --       | NE |
| Coutts |  --       | NE |
| Danske Bank |  --       | NE |
| First Trust Bank  |  --       | NE |
| Habib Bank |  --       | NE  |
| HSBC_trx |  --       | NE  |
| HSBC_pdf |  Done       | -- |
| Liberis Bank |  --       | NE |
| Lloyds_pdf |  --       | NE  |
| Lloys_trx |  Done       | --  |
| Metro Bank |  --       | NE  |
| Natwest_pdf |  Done       | --  |
| Natwest_trx |  Done       |  --  |
| RBS_trx |  --       | NE  |
| RBS_pdf |  Done       | --  |
| Santander_trx |  Done       | -- |
| Santander_pdf |  Done       | -- |
| TSB |  --       | NE |
| Yorkshire bank | Done      | -- |

NE : Not enough pdfs (Minimum 30 required)
Total of 532 NLP labelled text generated
